In [2]:
import pandas as pd
BTC=pd.read_csv("data/Bitcoin_hist.csv")
ETH = pd.read_csv("data/Ethereum_hist.csv")
AVL= pd.read_csv("data/Avalanche_hist.csv")
BIN= pd.read_csv("data/BinanceUSD_hist.csv")
BNB= pd.read_csv("data/BNB_hist.csv")
CAR= pd.read_csv("data/Cardano_hist.csv")
COS= pd.read_csv("data/Cosmos_hist.csv")
CRO= pd.read_csv("data/Cronos_hist.csv")
DAI= pd.read_csv("data/Dai_hist.csv")
DOG= pd.read_csv("data/Dogecoin_hist.csv")
PLK= pd.read_csv("data/Polkadot_hist.csv")
POL= pd.read_csv("data/Polygon_hist.csv")
SHI= pd.read_csv("data/ShibaInu_hist.csv")
SOL= pd.read_csv("data/Solana_hist.csv")
TER= pd.read_csv("data/Terra_hist.csv")
TETH= pd.read_csv("data/Tether_hist.csv")
USD= pd.read_csv("data/USDcoin_hist.csv")
WRAP= pd.read_csv("data/WrappedBitcoin_hist.csv")
XRP= pd.read_csv("data/XRP_hist.csv")

In [7]:
shape = BTC.shape
shape

(365, 9)

In [9]:
shape= ETH.shape
shape

(365, 9)

In [11]:
shape= AVL.shape
shape

(365, 9)

In [13]:
shape= BIN.shape
shape

(365, 9)

In [15]:
shape= BNB.shape
shape

(365, 9)

In [17]:
shape= CAR.shape
shape

(365, 9)

In [19]:
shape= COS.shape
shape

(365, 9)

In [21]:
shape= CRO.shape
shape

(365, 9)

In [23]:
shape= DAI.shape
shape

(365, 9)

In [25]:
shape= DOG.shape
shape

(365, 9)

In [27]:
shape= PLK.shape
shape

(365, 9)

In [29]:
shape= POL.shape
shape

(365, 9)

In [31]:
shape= SHI.shape
shape

(365, 9)

In [33]:
shape= SOL.shape
shape

(365, 9)

In [35]:
shape= TER.shape
shape

(365, 9)

In [37]:
shape= TETH.shape
shape

(365, 9)

In [39]:
shape= USD.shape
shape

(365, 9)

In [41]:
shape= WRAP.shape
shape

(365, 9)

In [43]:
shape= XRP.shape
shape

(365, 9)

In [17]:
ftr = BTC.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Bitcoin,BTC,"Feb 26, 2022","$39,213.08","$40,005.35","$38,702.53","$39,105.15","$17,467,554,129","$741,789,694,059"
1,Bitcoin,BTC,"Feb 25, 2022","$38,333.75","$39,630.32","$38,111.34","$39,214.22","$26,545,599,159","$743,827,806,938"
2,Bitcoin,BTC,"Feb 24, 2022","$37,278.57","$38,968.84","$34,459.22","$38,332.61","$46,383,802,093","$727,072,550,320"
3,Bitcoin,BTC,"Feb 23, 2022","$38,285.28","$39,122.39","$37,201.82","$37,296.57","$21,849,073,843","$707,390,766,255"
4,Bitcoin,BTC,"Feb 22, 2022","$37,068.77","$38,359.85","$36,488.93","$38,286.03","$25,493,150,450","$726,121,533,658"

In [47]:
ftr = ETH.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Ethereum,ETH,"Feb 26, 2022","$2,764.99","$2,849.42","$2,745.01","$2,781.11","$11,724,648,351","$333,024,181,663"
1,Ethereum,ETH,"Feb 25, 2022","$2,598.44","$2,821.97","$2,579.21","$2,764.54","$17,208,902,048","$331,001,574,996"
2,Ethereum,ETH,"Feb 24, 2022","$2,588.17","$2,689.05","$2,308.91","$2,598.07","$29,312,342,666","$311,035,019,270"
3,Ethereum,ETH,"Feb 23, 2022","$2,639.45","$2,741.37","$2,587.41","$2,590.36","$13,382,637,240","$310,077,026,340"
4,Ethereum,ETH,"Feb 22, 2022","$2,572.90","$2,648.92","$2,510.68","$2,639.30","$16,360,200,507","$315,899,223,813"

In [51]:
ftr = AVL.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Avalanche,AVAX,"Feb 26, 2022",$80.85,$84.87,$78.50,$81.88,"$1,419,135,253","$20,139,377,452"
1,Avalanche,AVAX,"Feb 25, 2022",$76.54,$81.86,$72.95,$80.83,"$1,884,195,969","$19,872,460,664"
2,Avalanche,AVAX,"Feb 24, 2022",$73.67,$79.32,$64.83,$76.52,"$3,097,306,165","$18,805,020,786"
3,Avalanche,AVAX,"Feb 23, 2022",$74.54,$81.84,$73.70,$73.70,"$1,699,396,767","$18,103,656,760"
4,Avalanche,AVAX,"Feb 22, 2022",$70.00,$74.76,$67.46,$74.57,"$1,344,001,591","$18,310,475,755"

In [53]:
ftr = BIN.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Binance USD,BUSD,"Feb 26, 2022",$1.00,$1.00,$0.9982,$1.00,"$3,994,663,167","$18,145,910,119"
1,Binance USD,BUSD,"Feb 25, 2022",$0.9997,$1.00,$0.9983,$1.00,"$5,625,014,132","$18,142,345,644"
2,Binance USD,BUSD,"Feb 24, 2022",$0.9997,$1.00,$0.9979,$0.9998,"$9,044,548,485","$18,549,890,792"
3,Binance USD,BUSD,"Feb 23, 2022",$1.00,$1.00,$0.9981,$0.9997,"$4,784,157,895","$18,260,533,543"
4,Binance USD,BUSD,"Feb 22, 2022",$0.9986,$1.00,$0.9977,$1.00,"$5,003,666,912","$18,303,896,641"

In [55]:
ftr = BNB.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,BNB,BNB,"Feb 26, 2022",$374.89,$385.21,$371.48,$373.64,"$1,319,208,551","$61,694,020,170"
1,BNB,BNB,"Feb 25, 2022",$361.22,$376.80,$357.37,$374.91,"$1,839,035,023","$61,904,739,647"
2,BNB,BNB,"Feb 24, 2022",$366.35,$368.17,$324.48,$361.23,"$2,972,951,900","$59,645,892,983"
3,BNB,BNB,"Feb 23, 2022",$374.30,$383.25,$366.54,$366.54,"$1,644,707,704","$60,521,812,716"
4,BNB,BNB,"Feb 22, 2022",$356.73,$374.86,$350.15,$374.31,"$2,037,210,077","$61,804,434,179"

In [57]:
ftr = CAR.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Cardano,ADA,"Feb 26, 2022",$0.898,$0.9283,$0.8854,$0.8879,"$1,099,934,921","$29,876,789,060"
1,Cardano,ADA,"Feb 25, 2022",$0.8536,$0.9065,$0.8292,$0.898,"$1,652,894,219","$30,210,158,117"
2,Cardano,ADA,"Feb 24, 2022",$0.8685,$0.8823,$0.7528,$0.8534,"$3,629,367,685","$28,709,774,071"
3,Cardano,ADA,"Feb 23, 2022",$0.889,$0.9554,$0.8692,$0.8692,"$1,824,386,011","$29,227,073,591"
4,Cardano,ADA,"Feb 22, 2022",$0.8581,$0.8938,$0.82,$0.889,"$2,058,499,639","$29,894,483,580"

In [59]:
ftr = COS.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Cosmos,ATOM,"Feb 26, 2022",$27.23,$30.29,$27.21,$29.81,"$1,069,523,684","$8,535,951,646"
1,Cosmos,ATOM,"Feb 25, 2022",$24.94,$27.40,$24.35,$27.23,"$898,558,382","$7,796,696,757"
2,Cosmos,ATOM,"Feb 24, 2022",$25.28,$25.48,$21.75,$24.95,"$1,378,414,997","$7,143,533,046"
3,Cosmos,ATOM,"Feb 23, 2022",$24.86,$26.86,$24.63,$25.29,"$787,914,536","$7,241,576,953"
4,Cosmos,ATOM,"Feb 22, 2022",$23.84,$24.95,$23.22,$24.86,"$704,566,874","$7,119,662,993"

In [61]:
ftr = CRO.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Cronos,CRO,"Feb 26, 2022",$0.4179,$0.4263,$0.4118,$0.4138,"$90,351,075","$10,452,967,044"
1,Cronos,CRO,"Feb 25, 2022",$0.3945,$0.4209,$0.3945,$0.4179,"$132,609,761","$10,556,215,610"
2,Cronos,CRO,"Feb 24, 2022",$0.399,$0.4042,$0.3477,$0.3945,"$220,041,913","$9,965,362,895"
3,Cronos,CRO,"Feb 23, 2022",$0.404,$0.4199,$0.3963,$0.3994,"$125,535,148","$10,088,882,959"
4,Cronos,CRO,"Feb 22, 2022",$0.3859,$0.405,$0.3711,$0.404,"$135,762,941","$10,205,910,036"

In [63]:
ftr = DAI.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Dai,DAI,"Feb 26, 2022",$0.9997,$1.00,$0.999,$1.00,"$205,336,506","$9,659,728,725"
1,Dai,DAI,"Feb 25, 2022",$1.00,$1.00,$0.999,$0.9997,"$330,433,421","$9,670,567,963"
2,Dai,DAI,"Feb 24, 2022",$0.9995,$1.00,$0.998,$1.00,"$646,259,155","$9,885,095,532"
3,Dai,DAI,"Feb 23, 2022",$1.00,$1.00,$0.9985,$0.9995,"$334,297,814","$10,072,492,019"
4,Dai,DAI,"Feb 22, 2022",$0.9994,$1.00,$0.9983,$1.00,"$358,833,503","$10,099,648,611"

In [65]:
ftr = DOG.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Dogecoin,DOGE,"Feb 26, 2022",$0.1276,$0.1301,$0.1262,$0.1276,"$535,575,654","$16,934,990,912"
1,Dogecoin,DOGE,"Feb 25, 2022",$0.1238,$0.1282,$0.121,$0.1276,"$805,161,073","$16,925,550,870"
2,Dogecoin,DOGE,"Feb 24, 2022",$0.1278,$0.1279,$0.1096,$0.1238,"$2,046,477,370","$16,426,325,929"
3,Dogecoin,DOGE,"Feb 23, 2022",$0.1316,$0.1353,$0.1278,$0.1278,"$587,472,906","$16,961,450,437"
4,Dogecoin,DOGE,"Feb 22, 2022",$0.1285,$0.1317,$0.1254,$0.1316,"$711,967,119","$17,453,195,149"

In [67]:
ftr = PLK.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Polkadot,DOT,"Feb 26, 2022",$17.25,$18.67,$17.22,$18.02,"$1,418,827,902","$17,800,681,672"
1,Polkadot,DOT,"Feb 25, 2022",$16.17,$17.41,$15.84,$17.25,"$1,228,501,074","$17,036,045,208"
2,Polkadot,DOT,"Feb 24, 2022",$16.00,$16.55,$14.14,$16.17,"$2,249,049,472","$15,970,062,776"
3,Polkadot,DOT,"Feb 23, 2022",$16.57,$17.40,$15.97,$16.01,"$1,280,516,751","$15,810,719,771"
4,Polkadot,DOT,"Feb 22, 2022",$16.19,$16.67,$15.84,$16.56,"$1,116,940,496","$16,358,536,727"

In [69]:
ftr = POL.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Polygon,MATIC,"Feb 26, 2022",$1.55,$1.59,$1.51,$1.52,"$898,567,950","$11,422,057,534"
1,Polygon,MATIC,"Feb 25, 2022",$1.44,$1.57,$1.41,$1.55,"$1,599,951,072","$11,688,571,514"
2,Polygon,MATIC,"Feb 24, 2022",$1.44,$1.49,$1.25,$1.44,"$2,679,134,468","$10,851,434,529"
3,Polygon,MATIC,"Feb 23, 2022",$1.46,$1.59,$1.44,$1.44,"$1,457,761,250","$10,864,359,620"
4,Polygon,MATIC,"Feb 22, 2022",$1.41,$1.47,$1.36,$1.46,"$1,347,670,062","$11,030,835,895"

In [71]:
ftr = SHI.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Shiba Inu,SHIB,"Feb 26, 2022",$0.00002483,$0.00002571,$0.00002429,$0.00002442,"$1,099,351,580","$13,407,920,359"
1,Shiba Inu,SHIB,"Feb 25, 2022",$0.00002386,$0.00002502,$0.00002315,$0.00002483,"$1,740,381,961","$13,633,916,782"
2,Shiba Inu,SHIB,"Feb 24, 2022",$0.00002499,$0.00002507,$0.00002087,$0.00002387,"$3,275,038,601","$13,105,005,934"
3,Shiba Inu,SHIB,"Feb 23, 2022",$0.00002496,$0.00002703,$0.00002466,$0.00002499,"$1,728,129,985","$13,722,000,038"
4,Shiba Inu,SHIB,"Feb 22, 2022",$0.00002408,$0.00002513,$0.00002325,$0.00002496,"$1,524,043,647","$13,705,662,514"

In [73]:
ftr = SOL.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Solana,SOL,"Feb 26, 2022",$92.61,$94.60,$89.76,$90.14,"$1,721,041,901","$28,838,878,173"
1,Solana,SOL,"Feb 25, 2022",$89.23,$94.78,$87.28,$92.60,"$3,069,242,551","$29,625,083,071"
2,Solana,SOL,"Feb 24, 2022",$84.86,$92.28,$76.86,$89.19,"$5,253,578,948","$28,536,069,022"
3,Solana,SOL,"Feb 23, 2022",$86.47,$92.74,$84.90,$84.90,"$2,293,962,445","$27,151,072,802"
4,Solana,SOL,"Feb 22, 2022",$83.11,$87.16,$81.20,$86.47,"$2,046,554,018","$27,650,979,801"

In [75]:
ftr = TER.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Terra,LUNA,"Feb 26, 2022",$73.16,$79.51,$72.42,$78.08,"$3,159,163,058","$29,621,245,348"
1,Terra,LUNA,"Feb 25, 2022",$65.37,$73.29,$64.06,$73.17,"$4,158,265,095","$27,868,114,968"
2,Terra,LUNA,"Feb 24, 2022",$59.63,$65.46,$50.52,$65.39,"$6,147,402,521","$25,017,719,459"
3,Terra,LUNA,"Feb 23, 2022",$54.77,$63.99,$54.71,$59.65,"$3,103,073,199","$22,977,426,376"
4,Terra,LUNA,"Feb 22, 2022",$50.16,$55.25,$48.59,$54.78,"$2,312,184,928","$21,195,466,382"

In [77]:
ftr = TETH.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Tether,USDT,"Feb 26, 2022",$1.00,$1.00,$1.00,$1.00,"$46,708,690,534","$79,571,654,148"
1,Tether,USDT,"Feb 25, 2022",$1.00,$1.00,$1.00,$1.00,"$66,025,345,539","$79,521,157,340"
2,Tether,USDT,"Feb 24, 2022",$1.00,$1.00,$1.00,$1.00,"$107,952,010,250","$79,525,180,253"
3,Tether,USDT,"Feb 23, 2022",$1.00,$1.00,$1.00,$1.00,"$54,845,607,157","$79,454,771,411"
4,Tether,USDT,"Feb 22, 2022",$1.00,$1.00,$1.00,$1.00,"$60,539,262,856","$79,410,542,602"

In [79]:
ftr = USD.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,USD Coin,USDC,"Feb 26, 2022",$0.9999,$1.00,$0.9991,$1,"$3,262,045,031","$53,290,419,666"
1,USD Coin,USDC,"Feb 25, 2022",$0.9999,$1.00,$0.9993,$0.9999,"$5,563,465,156","$53,268,559,752"
2,USD Coin,USDC,"Feb 24, 2022",$0.9995,$1.00,$0.9988,$1,"$9,044,960,990","$53,126,695,517"
3,USD Coin,USDC,"Feb 23, 2022",$1.00,$1.00,$0.9989,$0.9995,"$4,088,593,001","$52,797,597,466"
4,USD Coin,USDC,"Feb 22, 2022",$0.9994,$1.00,$0.9988,$1.00,"$4,311,028,906","$52,724,134,665"

In [81]:
ftr = WRAP.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Wrapped Bitcoin,WBTC,"Feb 26, 2022","$39,236.82","$39,863.65","$38,818.91","$39,068.00","$149,601,888","$10,265,593,124"
1,Wrapped Bitcoin,WBTC,"Feb 25, 2022","$38,277.17","$39,508.94","$38,203.45","$39,243.11","$325,327,024","$10,311,605,735"
2,Wrapped Bitcoin,WBTC,"Feb 24, 2022","$37,256.68","$38,759.47","$34,573.51","$38,276.02","$461,473,124","$10,072,801,562"
3,Wrapped Bitcoin,WBTC,"Feb 23, 2022","$38,231.15","$39,082.69","$37,230.61","$37,260.75","$150,897,606","$9,805,622,367"
4,Wrapped Bitcoin,WBTC,"Feb 22, 2022","$37,089.52","$38,264.43","$36,545.87","$38,230.69","$188,206,786","$10,060,873,033"

In [83]:
ftr = XRP.head()
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,XRP,XRP,"Feb 26, 2022",$0.7686,$0.7882,$0.7436,$0.751,"$3,051,695,701","$36,008,637,870"
1,XRP,XRP,"Feb 25, 2022",$0.6963,$0.7689,$0.6858,$0.7689,"$3,460,713,330","$36,868,338,077"
2,XRP,XRP,"Feb 24, 2022",$0.6986,$0.7129,$0.6271,$0.6963,"$5,146,799,150","$33,385,746,487"
3,XRP,XRP,"Feb 23, 2022",$0.7229,$0.7389,$0.6963,$0.6987,"$2,690,184,820","$33,504,378,574"
4,XRP,XRP,"Feb 22, 2022",$0.7033,$0.7252,$0.6788,$0.7228,"$3,539,593,096","$34,659,333,456"

In [85]:
most = BTC.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,365,365,365,365,365,365
top,Bitcoin,BTC,"Feb 26, 2022","$39,213.08","$40,005.35","$38,702.53","$39,105.15","$17,467,554,129","$741,789,694,059"
freq,365,365,1,1,1,1,1,1,1

In [87]:
most = ETH.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,365,365,365,365,365,365
top,Ethereum,ETH,"Feb 26, 2022","$2,764.99","$2,849.42","$2,745.01","$2,781.11","$11,724,648,351","$333,024,181,663"
freq,365,365,1,1,1,1,1,1,1

In [91]:
most = AVL.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,353,358,361,356,365,365
top,Avalanche,AVAX,"Feb 26, 2022",$32.81,$12.09,$12.65,$36.82,"$1,419,135,253","$20,139,377,452"
freq,365,365,1,2,2,2,2,1,1

In [93]:
most = BIN.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,18,5,29,20,365,365
top,Binance USD,BUSD,"Feb 26, 2022",$1.00,$1.00,$0.9998,$1.00,"$3,994,663,167","$18,145,910,119"
freq,365,365,1,222,359,62,229,1,1

In [95]:
most = BNB.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,365,363,363,364,365,365
top,BNB,BNB,"Feb 26, 2022",$374.89,$387.77,$309.14,$549.59,"$1,319,208,551","$61,694,020,170"
freq,365,365,1,1,2,2,2,1,1

In [97]:
most = CAR.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,145,145,143,152,365,365
top,Cardano,ADA,"Feb 26, 2022",$1.19,$1.35,$1.20,$1.19,"$1,099,934,921","$29,876,789,060"
freq,365,365,1,10,9,14,9,1,1

In [99]:
most = COS.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,350,337,352,342,365,365
top,Cosmos,ATOM,"Feb 26, 2022",$28.13,$19.21,$19.55,$19.64,"$1,069,523,684","$8,535,951,646"
freq,365,365,1,2,3,2,3,1,1

In [101]:
most = CRO.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,334,342,337,333,365,365
top,Cronos,CRO,"Feb 26, 2022",$0.1886,$0.1988,$0.15,$0.1875,"$90,351,075","$10,452,967,044"
freq,365,365,1,3,3,3,3,1,1

In [103]:
most = DAI.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,27,7,63,29,365,365
top,Dai,DAI,"Feb 26, 2022",$1.00,$1.00,$1.00,$1.00,"$205,336,506","$9,659,728,725"
freq,365,365,1,272,304,76,269,1,1

In [105]:
most = DOG.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,345,349,340,346,365,365
top,Dogecoin,DOGE,"Feb 26, 2022",$0.2332,$0.1744,$0.1369,$0.1276,"$535,575,654","$16,934,990,912"
freq,365,365,1,2,2,3,2,1,1

In [107]:
most = PLK.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,353,349,351,341,365,365
top,Polkadot,DOT,"Feb 26, 2022",$25.19,$43.11,$40.16,$18.02,"$1,418,827,902","$17,800,681,672"
freq,365,365,1,2,2,2,2,1,1

In [109]:
most = POL.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,210,214,212,210,365,365
top,Polygon,MATIC,"Feb 26, 2022",$1.08,$1.68,$1.04,$1.05,"$898,567,950","$11,422,057,534"
freq,365,365,1,7,6,6,8,1,1

In [111]:
most = SHI.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,306,315,303,307,365,296
top,Shiba Inu,SHIB,"Feb 26, 2022",$0.00000002,$0.00000002,$0.00000002,$0.00000002,"$1,099,351,580",$0
freq,365,365,1,11,9,11,11,1,70

In [113]:
most = SOL.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,358,362,355,352,365,365
top,Solana,SOL,"Feb 26, 2022",$34.02,$35.50,$43.30,$31.28,"$1,721,041,901","$28,838,878,173"
freq,365,365,1,2,2,2,3,1,1

In [115]:
most = TER.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,338,347,349,345,365,365
top,Terra,LUNA,"Feb 26, 2022",$7.89,$6.56,$15.19,$5.92,"$3,159,163,058","$29,621,245,348"
freq,365,365,1,3,3,2,3,1,1

In [117]:
most = TETH.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,13,4,23,13,365,365
top,Tether,USDT,"Feb 26, 2022",$1.00,$1.00,$1.00,$1.00,"$46,708,690,534","$79,571,654,148"
freq,365,365,1,308,359,125,315,1,1

In [119]:
most = USD.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,17,6,21,17,365,365
top,USD Coin,USDC,"Feb 26, 2022",$1.00,$1.00,$0.9998,$1.00,"$3,262,045,031","$53,290,419,666"
freq,365,365,1,222,358,60,222,1,1

In [121]:
most = WRAP.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,365,365,365,365,365,365
top,Wrapped Bitcoin,WBTC,"Feb 26, 2022","$39,236.82","$39,863.65","$38,818.91","$39,068.00","$149,601,888","$10,265,593,124"
freq,365,365,1,1,1,1,1,1,1

In [123]:
most = XRP.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,265,262,277,267,365,365
top,XRP,XRP,"Feb 26, 2022",$1.09,$1.10,$1.06,$1.09,"$3,051,695,701","$36,008,637,870"
freq,365,365,1,13,11,11,12,1,1

In [125]:
nullcheck = BTC.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [127]:
nullcheck = ETH.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [129]:
nullcheck = AVL.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [131]:
nullcheck = BIN.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [133]:
nullcheck = BNB.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [135]:
nullcheck = CAR.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [137]:
nullcheck = COS.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [139]:
nullcheck = CRO.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [141]:
nullcheck = DAI.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [143]:
nullcheck = DOG.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [145]:
nullcheck = PLK.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [147]:
nullcheck = POL.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [149]:
nullcheck = SHI.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [151]:
nullcheck = SOL.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [153]:
nullcheck = TER.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [155]:
nullcheck = TETH.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [157]:
nullcheck = USD.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [159]:
nullcheck = WRAP.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [161]:
nullcheck = XRP.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True

In [6]:
import os
import pandas as pd

def clean_crypto_csvs(folder_path="data"):
    for filename in os.listdir(folder_path):
        if filename.endswith("_hist.csv"):
            filepath = os.path.join(folder_path, filename)
            try:
                df = pd.read_csv(filepath)

                for col in ["open_price", "high", "low", "close_price", "volume", "market_cap"]:
                    if col in df.columns:
                        df[col] = df[col].replace({r'\$': '', ',': ''}, regex=True).astype(float)

                if "date" in df.columns:
                    df["date"] = pd.to_datetime(df["date"])

                df.to_csv(filepath, index=False)
                print(f"[✓] Cleaned: {filename}")

            except Exception as e:
                print(f"[!] Failed to clean {filename}: {e}")

In [10]:
clean_crypto_csvs("data")

[✓] Cleaned: Avalanche_hist.csv
[✓] Cleaned: BinanceUSD_hist.csv
[✓] Cleaned: Bitcoin_hist.csv
[✓] Cleaned: BNB_hist.csv
[✓] Cleaned: Cardano_hist.csv
[✓] Cleaned: Cosmos_hist.csv
[✓] Cleaned: Cronos_hist.csv
[✓] Cleaned: Dai_hist.csv
[✓] Cleaned: Dogecoin_hist.csv
[✓] Cleaned: Ethereum_hist.csv
[✓] Cleaned: Polkadot_hist.csv
[✓] Cleaned: Polygon_hist.csv
[✓] Cleaned: ShibaInu_hist.csv
[✓] Cleaned: Solana_hist.csv
[✓] Cleaned: Terra_hist.csv
[✓] Cleaned: Tether_hist.csv
[✓] Cleaned: USDCoin_hist.csv
[✓] Cleaned: WrappedBitcoin_hist.csv
[✓] Cleaned: XRP_hist.csv

In [3]:
ftr = BTC.head(10)
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Bitcoin,BTC,2022-02-26,39213.08,40005.35,38702.53,39105.15,1.746755e+10,7.417897e+11
1,Bitcoin,BTC,2022-02-25,38333.75,39630.32,38111.34,39214.22,2.654560e+10,7.438278e+11
2,Bitcoin,BTC,2022-02-24,37278.57,38968.84,34459.22,38332.61,4.638380e+10,7.270726e+11
3,Bitcoin,BTC,2022-02-23,38285.28,39122.39,37201.82,37296.57,2.184907e+10,7.073908e+11
4,Bitcoin,BTC,2022-02-22,37068.77,38359.85,36488.93,38286.03,2.549315e+10,7.261215e+11
5,Bitcoin,BTC,2022-02-21,38423.21,39394.44,36950.48,37075.28,2.928040e+10,7.031241e+11
6,Bitcoin,BTC,2022-02-20,40118.10,40119.89,38112.81,38431.38,1.834058e+10,7.288124e+11
7,Bitcoin,BTC,2022-02-19,40026.02,40418.88,39713.06,40122.15,1.373656e+10,7.608394e+11
8,Bitcoin,BTC,2022-02-18,40552.13,40929.15,39637.62,40030.98,2.331001e+10,7.590741e+11
9,Bitcoin,BTC,2022-02-17,43937.07,44132.97,40249.37,40538.01,2.624666e+10,7.686544e+11